### ISSUE TITLE
Does this library work in browser ?

### ISSUE THREAD

**Issue by ananth-minions** [universe-ai/pocket-sockets#1]
I'm much interested in learning about this package and the description of this repo in [README.md](https://github.com/universe-ai/pocket-sockets/blob/master/README.md) got attention.
As I need to establish a TCP (socket) connection with printers (yes it is not a browser, and do not have Node.js environment) over the network (with a specific host and port), and then use the client to send buffer to the targeted printer (yes my printer supports TCP/IP).

While googling I came across this repo and had the following questions.

Would mind answering my queries?

- [ ] I knew that with node's [`net`](https://nodejs.org/api/net.html) module we can communicate with the devices which support TCP/IP, but this is limited to Node.js environments. Can I use your library on the browser side, without any additional dependencies? 
- [ ] I see `ws` is used as a dependency in your library, doesn't it restrict the usage to Node.js-based environments. I referred to browser support notes [here](https://github.com/websockets/ws#ws-a-nodejs-websocket-library)
- [ ] I see some certificate configurations in the code itself, doesn't it restrict the library usage to specific projects. may be projects related to universe.ai

Thanks in advance!

**Comment by filippsen** [comment]
Hi Ananth,

This library intends to serve the purpose of allowing browser-based or node.js-based clients to connect to a server through _WebSocket_ communication or _TCP_ via a common _API_. However, the _TCP_ route is only available when running via the _Node.js_ runtime.
That way, when going the browser route, both client and server sockets have to be of type _WebSocket_ in order for it to work.

About the questions:
1. No, `net` module won't work in the browser. That module does serve the purpose of handling _TCP_ connections, but it requires the _Node.js_ runtime. 
2. `ws` is listed as a dependency to enable _Node.js_-based clients to connect via _WebSocket_, like provided by and done in browser environments. When the target is identified as "browser", then it uses whatever is available. See also: https://github.com/universe-ai/pocket-sockets/blob/master/WSClient.js#L6
3. Certificate configurations are required when using _TLS_ and secure connections. They are optional when creating a server and only required when connecting to a secured server.

I'm afraid this project won't fit the exact requirements as you listed. As an alternative, perhaps consider looking at browser-specific APIs, your own plugins/addons or some other locally available route for TCP connections in the browser.
Thanks for reaching out

**Comment by ananth-minions** [comment]
@filippsen , Thank you so much for the reply and resolutions :smiling_face_with_three_hearts: 

I'm closing this issue
